# サイトの基本設定
baseURL = "https://usermiyam.github.io/MiyaLab-OutputBlog/"
languageCode = "ja-jp"
title = "MiyaLab-OutputBlog"
theme = "my-custom-theme"  # 自分のテーマ名に変える
publishDir = "docs"        # ここでdocsに出力する設定

# コンテンツと公開先のディレクトリ設定
contentDir = "content"


# ヘッダーに表示するメニュー
[[menu.main]]
  name = "Paiza"
  url = "/docs/paiza/"
  weight = 10

[[menu.main]]
  name = "Atcoder"
  url = "/docs/atcoder/"
  weight = 20

[[menu.main]]
  name = "Go言語"
  url = "/docs/go/"
  weight = 30