# サイトの基本設定
baseURL = "http://localhost:1313/"
# baseURL = "https://UserMiyam.github.io/MiyaLab-OutputBlog/"
languageCode = "ja-jp"
# theme = "hugo-book"
theme = "my-custom-theme"

# コンテンツと公開先のディレクトリ設定
contentDir = "content"
publishDir = "docs"


# ヘッダーに表示するメニュー
[[menu.main]]
  name = "Paiza"
  url = "/docs/paiza/"
  weight = 10

[[menu.main]]
  name = "Atcoder"
  url = "/docs/atcoder/"
  weight = 20

[[menu.main]]
  name = "Go言語"
  url = "/docs/go/"
  weight = 30