name: Build with Hugo
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:  # matrix削除でシンプルに
      - uses: actions/checkout@v4
        with:
          submodules: true  # Fetch Hugo themes
          fetch-depth: 0    # Fetch all history

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: 'latest'  # 0.146.7を避けて安定版
          extended: true

      - name: Run Hugo
        working-directory: exampleSite
        run: hugo --minify --gc  # --themesDir削除。config.tomlで設定

      # - name: Deploy  # 公開時有効化
      #   uses: peaceiris/actions-gh-pages@v3
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     publish_dir: ./public